[tool.poetry]
name = "data-science-project-template"
version = "0.1.0"
description = "Template for a data science projects with software development tools"
authors = ["Jose R. Zapata <https://joserzapata.github.io/>"]
repository = "https://github.com/JoseRZapata/data-science-project-template"
license = "MIT"
readme = "README.md"
keywords = ["data-science","cookiecutter", "poetry"]

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
