repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.9
    hooks:
      # Run the linter.s
      - id: ruff
        args:
          - --config
          - .code_quality/ruff.toml      # Run the formatter.
      - id: ruff-format
        args:
          - --config
          - .code_quality/ruff.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        args:
          - --config-file=.code_quality/mypy.ini

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
    -   id: bandit
        args:
          - -c
          - .code_quality/bandit.yaml
