name: Docs

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - name: Deploy docs
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/JoseRZapata/data-science-project-template.git
          poetry run mkdocs gh-deploy --force
