name: Docs

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: ./.github/actions/python-poetry-env
      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force
