name: Docs

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - name: Deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: poetry run mkdocs gh-deploy --force
