name: Docs

on:
  pull_request:
    types:
      - closed
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force
